# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnergyAuditor.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EnergyAuditor(object):
    def setupUi(self, EnergyAuditor):
        EnergyAuditor.setObjectName("EnergyAuditor")
        EnergyAuditor.setEnabled(True)
        EnergyAuditor.resize(762, 632)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        EnergyAuditor.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EnergyAuditor.setWindowIcon(icon)
        EnergyAuditor.setWindowOpacity(7.0)
        EnergyAuditor.setAutoFillBackground(True)
        EnergyAuditor.setStyleSheet("")
        self.refreshButton = QtWidgets.QPushButton(EnergyAuditor)
        self.refreshButton.setGeometry(QtCore.QRect(140, 530, 51, 51))
        self.refreshButton.setStyleSheet("")
        self.refreshButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/refreshbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon1)
        self.refreshButton.setIconSize(QtCore.QSize(35, 35))
        self.refreshButton.setAutoDefault(False)
        self.refreshButton.setDefault(False)
        self.refreshButton.setFlat(False)
        self.refreshButton.setObjectName("refreshButton")
        self.exitButton = QtWidgets.QPushButton(EnergyAuditor)
        self.exitButton.setGeometry(QtCore.QRect(590, 530, 51, 51))
        self.exitButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/powerbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon2)
        self.exitButton.setIconSize(QtCore.QSize(42, 42))
        self.exitButton.setAutoDefault(False)
        self.exitButton.setDefault(False)
        self.exitButton.setFlat(False)
        self.exitButton.setObjectName("exitButton")
        self.node1TimeLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node1TimeLabel.setGeometry(QtCore.QRect(105, 255, 51, 51))
        self.node1TimeLabel.setText("")
        self.node1TimeLabel.setPixmap(QtGui.QPixmap("Images/clock.png"))
        self.node1TimeLabel.setObjectName("node1TimeLabel")
        self.node1TimeDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1TimeDisplay.setGeometry(QtCore.QRect(60, 315, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1TimeDisplay.setFont(font)
        self.node1TimeDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node1TimeDisplay.setObjectName("node1TimeDisplay")
        self.node1Status = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1Status.setGeometry(QtCore.QRect(190, 195, 16, 16))
        self.node1Status.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.node1Status.setObjectName("node1Status")
        self.sensorStatus = QtWidgets.QLineEdit(EnergyAuditor)
        self.sensorStatus.setGeometry(QtCore.QRect(195, 520, 12, 12))
        self.sensorStatus.setAutoFillBackground(False)
        self.sensorStatus.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sensorStatus.setObjectName("sensorStatus")
        self.graphButton = QtWidgets.QPushButton(EnergyAuditor)
        self.graphButton.setGeometry(QtCore.QRect(365, 530, 51, 51))
        self.graphButton.setAutoFillBackground(False)
        self.graphButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.graphButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphButton.setIcon(icon3)
        self.graphButton.setIconSize(QtCore.QSize(40, 40))
        self.graphButton.setCheckable(True)
        self.graphButton.setFlat(False)
        self.graphButton.setObjectName("graphButton")
        self.node2TimeDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node2TimeDisplay.setGeometry(QtCore.QRect(320, 320, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node2TimeDisplay.setFont(font)
        self.node2TimeDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node2TimeDisplay.setObjectName("node2TimeDisplay")
        self.node3TimeDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node3TimeDisplay.setGeometry(QtCore.QRect(565, 315, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node3TimeDisplay.setFont(font)
        self.node3TimeDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node3TimeDisplay.setObjectName("node3TimeDisplay")
        self.applicationLogo = QtWidgets.QLabel(EnergyAuditor)
        self.applicationLogo.setGeometry(QtCore.QRect(2, 1, 759, 140))
        self.applicationLogo.setFrameShape(QtWidgets.QFrame.Box)
        self.applicationLogo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.applicationLogo.setLineWidth(1)
        self.applicationLogo.setText("")
        self.applicationLogo.setPixmap(QtGui.QPixmap("Images/energyAuditor.png"))
        self.applicationLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.applicationLogo.setOpenExternalLinks(True)
        self.applicationLogo.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.applicationLogo.setObjectName("applicationLogo")
        self.node2TimeLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node2TimeLabel.setGeometry(QtCore.QRect(365, 260, 51, 51))
        self.node2TimeLabel.setText("")
        self.node2TimeLabel.setPixmap(QtGui.QPixmap("Images/clock.png"))
        self.node2TimeLabel.setObjectName("node2TimeLabel")
        self.node2Status = QtWidgets.QLineEdit(EnergyAuditor)
        self.node2Status.setGeometry(QtCore.QRect(455, 195, 16, 16))
        self.node2Status.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.node2Status.setObjectName("node2Status")
        self.node3TimeLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node3TimeLabel.setGeometry(QtCore.QRect(610, 255, 51, 51))
        self.node3TimeLabel.setText("")
        self.node3TimeLabel.setPixmap(QtGui.QPixmap("Images/clock.png"))
        self.node3TimeLabel.setObjectName("node3TimeLabel")
        self.node3Status = QtWidgets.QLineEdit(EnergyAuditor)
        self.node3Status.setGeometry(QtCore.QRect(690, 195, 16, 16))
        self.node3Status.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.node3Status.setObjectName("node3Status")
        self.node1Label = QtWidgets.QLabel(EnergyAuditor)
        self.node1Label.setGeometry(QtCore.QRect(30, 155, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node1Label.setFont(font)
        self.node1Label.setFrameShape(QtWidgets.QFrame.Box)
        self.node1Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.node1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.node1Label.setObjectName("node1Label")
        self.line = QtWidgets.QFrame(EnergyAuditor)
        self.line.setGeometry(QtCore.QRect(245, 140, 20, 351))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(EnergyAuditor)
        self.line_2.setGeometry(QtCore.QRect(500, 140, 20, 351))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(EnergyAuditor)
        self.line_3.setGeometry(QtCore.QRect(0, 480, 761, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(EnergyAuditor)
        self.line_4.setGeometry(QtCore.QRect(0, 132, 761, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.node2Label = QtWidgets.QLabel(EnergyAuditor)
        self.node2Label.setGeometry(QtCore.QRect(285, 155, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node2Label.setFont(font)
        self.node2Label.setFrameShape(QtWidgets.QFrame.Box)
        self.node2Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.node2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.node2Label.setObjectName("node2Label")
        self.node3Label = QtWidgets.QLabel(EnergyAuditor)
        self.node3Label.setGeometry(QtCore.QRect(540, 155, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node3Label.setFont(font)
        self.node3Label.setFrameShape(QtWidgets.QFrame.Box)
        self.node3Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.node3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.node3Label.setObjectName("node3Label")
        self.node2CurrentLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node2CurrentLabel.setGeometry(QtCore.QRect(300, 382, 46, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node2CurrentLabel.setFont(font)
        self.node2CurrentLabel.setText("")
        self.node2CurrentLabel.setPixmap(QtGui.QPixmap("Images/current.png"))
        self.node2CurrentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.node2CurrentLabel.setObjectName("node2CurrentLabel")
        self.node2PowerLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node2PowerLabel.setGeometry(QtCore.QRect(420, 375, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node2PowerLabel.setFont(font)
        self.node2PowerLabel.setText("")
        self.node2PowerLabel.setPixmap(QtGui.QPixmap("Images/power.png"))
        self.node2PowerLabel.setObjectName("node2PowerLabel")
        self.node3CurrentLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node3CurrentLabel.setGeometry(QtCore.QRect(550, 382, 46, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node3CurrentLabel.setFont(font)
        self.node3CurrentLabel.setText("")
        self.node3CurrentLabel.setPixmap(QtGui.QPixmap("Images/current.png"))
        self.node3CurrentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.node3CurrentLabel.setObjectName("node3CurrentLabel")
        self.node3PowerLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node3PowerLabel.setGeometry(QtCore.QRect(670, 375, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node3PowerLabel.setFont(font)
        self.node3PowerLabel.setText("")
        self.node3PowerLabel.setPixmap(QtGui.QPixmap("Images/power.png"))
        self.node3PowerLabel.setObjectName("node3PowerLabel")
        self.node1CurrentLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node1CurrentLabel.setGeometry(QtCore.QRect(45, 382, 46, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node1CurrentLabel.setFont(font)
        self.node1CurrentLabel.setText("")
        self.node1CurrentLabel.setPixmap(QtGui.QPixmap("Images/current.png"))
        self.node1CurrentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.node1CurrentLabel.setObjectName("node1CurrentLabel")
        self.node1PowerLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node1PowerLabel.setGeometry(QtCore.QRect(165, 375, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node1PowerLabel.setFont(font)
        self.node1PowerLabel.setText("")
        self.node1PowerLabel.setPixmap(QtGui.QPixmap("Images/power.png"))
        self.node1PowerLabel.setObjectName("node1PowerLabel")
        self.node1AddressDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1AddressDisplay.setGeometry(QtCore.QRect(75, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1AddressDisplay.setFont(font)
        self.node1AddressDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node1AddressDisplay.setObjectName("node1AddressDisplay")
        self.node2AddressDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node2AddressDisplay.setGeometry(QtCore.QRect(330, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node2AddressDisplay.setFont(font)
        self.node2AddressDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node2AddressDisplay.setObjectName("node2AddressDisplay")
        self.node3AddressDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node3AddressDisplay.setGeometry(QtCore.QRect(575, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node3AddressDisplay.setFont(font)
        self.node3AddressDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node3AddressDisplay.setObjectName("node3AddressDisplay")
        self.node1CurrentDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1CurrentDisplay.setGeometry(QtCore.QRect(15, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1CurrentDisplay.setFont(font)
        self.node1CurrentDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node1CurrentDisplay.setObjectName("node1CurrentDisplay")
        self.node1PowerDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1PowerDisplay.setGeometry(QtCore.QRect(140, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1PowerDisplay.setFont(font)
        self.node1PowerDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node1PowerDisplay.setObjectName("node1PowerDisplay")
        self.node2CurrentDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node2CurrentDisplay.setGeometry(QtCore.QRect(270, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node2CurrentDisplay.setFont(font)
        self.node2CurrentDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node2CurrentDisplay.setObjectName("node2CurrentDisplay")
        self.node2PowerDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node2PowerDisplay.setGeometry(QtCore.QRect(395, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node2PowerDisplay.setFont(font)
        self.node2PowerDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node2PowerDisplay.setObjectName("node2PowerDisplay")
        self.node3CurrentDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node3CurrentDisplay.setGeometry(QtCore.QRect(525, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node3CurrentDisplay.setFont(font)
        self.node3CurrentDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node3CurrentDisplay.setObjectName("node3CurrentDisplay")
        self.node3PowerDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node3PowerDisplay.setGeometry(QtCore.QRect(645, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node3PowerDisplay.setFont(font)
        self.node3PowerDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node3PowerDisplay.setObjectName("node3PowerDisplay")
        self.applicationLogo2 = QtWidgets.QLabel(EnergyAuditor)
        self.applicationLogo2.setGeometry(QtCore.QRect(630, 30, 121, 91))
        self.applicationLogo2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.applicationLogo2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.applicationLogo2.setLineWidth(1)
        self.applicationLogo2.setText("")
        self.applicationLogo2.setPixmap(QtGui.QPixmap("Images/culogo.png"))
        self.applicationLogo2.setAlignment(QtCore.Qt.AlignCenter)
        self.applicationLogo2.setObjectName("applicationLogo2")
        self.documentationLink = QtWidgets.QLabel(EnergyAuditor)
        self.documentationLink.setGeometry(QtCore.QRect(0, 600, 761, 31))
        self.documentationLink.setFrameShape(QtWidgets.QFrame.Box)
        self.documentationLink.setAlignment(QtCore.Qt.AlignCenter)
        self.documentationLink.setWordWrap(False)
        self.documentationLink.setOpenExternalLinks(False)
        self.documentationLink.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.documentationLink.setObjectName("documentationLink")
        self.elapsedTime = QtWidgets.QLCDNumber(EnergyAuditor)
        self.elapsedTime.setGeometry(QtCore.QRect(40, 80, 81, 31))
        self.elapsedTime.setObjectName("elapsedTime")
        self.elapsedTimeLabel = QtWidgets.QLabel(EnergyAuditor)
        self.elapsedTimeLabel.setGeometry(QtCore.QRect(10, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.elapsedTimeLabel.setFont(font)
        self.elapsedTimeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.elapsedTimeLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.elapsedTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.elapsedTimeLabel.setObjectName("elapsedTimeLabel")
        self.node1_Number = QtWidgets.QLCDNumber(EnergyAuditor)
        self.node1_Number.setGeometry(QtCore.QRect(200, 155, 21, 31))
        self.node1_Number.setDigitCount(1)
        self.node1_Number.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.node1_Number.setProperty("intValue", 0)
        self.node1_Number.setObjectName("node1_Number")
        self.node2_Number = QtWidgets.QLCDNumber(EnergyAuditor)
        self.node2_Number.setGeometry(QtCore.QRect(460, 155, 21, 31))
        self.node2_Number.setDigitCount(1)
        self.node2_Number.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.node2_Number.setObjectName("node2_Number")
        self.node3_Number = QtWidgets.QLCDNumber(EnergyAuditor)
        self.node3_Number.setGeometry(QtCore.QRect(700, 155, 21, 31))
        self.node3_Number.setDigitCount(1)
        self.node3_Number.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.node3_Number.setObjectName("node3_Number")

        self.retranslateUi(EnergyAuditor)
        QtCore.QMetaObject.connectSlotsByName(EnergyAuditor)

    def retranslateUi(self, EnergyAuditor):
        _translate = QtCore.QCoreApplication.translate
        EnergyAuditor.setWindowTitle(_translate("EnergyAuditor", "Energy Auditor"))
        self.node1Label.setText(_translate("EnergyAuditor", "SENSOR NODE"))
        self.node2Label.setText(_translate("EnergyAuditor", "SENSOR NODE"))
        self.node3Label.setText(_translate("EnergyAuditor", "SENSOR NODE"))
        self.documentationLink.setText(_translate("EnergyAuditor", "https://github.com/hpreshit/Energy-Auditor"))
        self.elapsedTimeLabel.setText(_translate("EnergyAuditor", "Time Elapsed"))

