# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnergyAuditor.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EnergyAuditor(object):
    def setupUi(self, EnergyAuditor):
        EnergyAuditor.setObjectName("EnergyAuditor")
        EnergyAuditor.setEnabled(True)
        EnergyAuditor.resize(762, 634)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        EnergyAuditor.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EnergyAuditor.setWindowIcon(icon)
        EnergyAuditor.setWindowOpacity(7.0)
        EnergyAuditor.setAutoFillBackground(True)
        EnergyAuditor.setStyleSheet("")
        self.refreshButton = QtWidgets.QPushButton(EnergyAuditor)
        self.refreshButton.setGeometry(QtCore.QRect(140, 530, 51, 51))
        self.refreshButton.setStyleSheet("")
        self.refreshButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/refreshbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon1)
        self.refreshButton.setIconSize(QtCore.QSize(35, 35))
        self.refreshButton.setAutoDefault(False)
        self.refreshButton.setDefault(False)
        self.refreshButton.setFlat(False)
        self.refreshButton.setObjectName("refreshButton")
        self.exitButton = QtWidgets.QPushButton(EnergyAuditor)
        self.exitButton.setGeometry(QtCore.QRect(590, 530, 51, 51))
        self.exitButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/powerbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon2)
        self.exitButton.setIconSize(QtCore.QSize(42, 42))
        self.exitButton.setAutoDefault(False)
        self.exitButton.setDefault(False)
        self.exitButton.setFlat(False)
        self.exitButton.setObjectName("exitButton")
        self.node1TimeLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node1TimeLabel.setGeometry(QtCore.QRect(110, 255, 51, 51))
        self.node1TimeLabel.setText("")
        self.node1TimeLabel.setPixmap(QtGui.QPixmap("Images/clock.png"))
        self.node1TimeLabel.setObjectName("node1TimeLabel")
        self.node1TimeDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1TimeDisplay.setGeometry(QtCore.QRect(75, 315, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1TimeDisplay.setFont(font)
        self.node1TimeDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node1TimeDisplay.setObjectName("node1TimeDisplay")
        self.node1Status = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1Status.setGeometry(QtCore.QRect(190, 195, 16, 16))
        self.node1Status.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.node1Status.setObjectName("node1Status")
        self.sensorStatus = QtWidgets.QLineEdit(EnergyAuditor)
        self.sensorStatus.setGeometry(QtCore.QRect(195, 520, 12, 12))
        self.sensorStatus.setAutoFillBackground(False)
        self.sensorStatus.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sensorStatus.setObjectName("sensorStatus")
        self.graphButton = QtWidgets.QPushButton(EnergyAuditor)
        self.graphButton.setGeometry(QtCore.QRect(365, 530, 51, 51))
        self.graphButton.setAutoFillBackground(False)
        self.graphButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.graphButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphButton.setIcon(icon3)
        self.graphButton.setIconSize(QtCore.QSize(40, 40))
        self.graphButton.setCheckable(True)
        self.graphButton.setFlat(False)
        self.graphButton.setObjectName("graphButton")
        self.node2TimeDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node2TimeDisplay.setGeometry(QtCore.QRect(340, 320, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node2TimeDisplay.setFont(font)
        self.node2TimeDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node2TimeDisplay.setObjectName("node2TimeDisplay")
        self.node3TimeDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node3TimeDisplay.setGeometry(QtCore.QRect(575, 315, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node3TimeDisplay.setFont(font)
        self.node3TimeDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node3TimeDisplay.setObjectName("node3TimeDisplay")
        self.applicationLogo = QtWidgets.QLabel(EnergyAuditor)
        self.applicationLogo.setGeometry(QtCore.QRect(295, 20, 193, 111))
        self.applicationLogo.setFrameShape(QtWidgets.QFrame.Panel)
        self.applicationLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.applicationLogo.setLineWidth(2)
        self.applicationLogo.setText("")
        self.applicationLogo.setPixmap(QtGui.QPixmap("Images/energyAuditor.png"))
        self.applicationLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.applicationLogo.setObjectName("applicationLogo")
        self.node2TimeLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node2TimeLabel.setGeometry(QtCore.QRect(370, 260, 51, 51))
        self.node2TimeLabel.setText("")
        self.node2TimeLabel.setPixmap(QtGui.QPixmap("Images/clock.png"))
        self.node2TimeLabel.setObjectName("node2TimeLabel")
        self.node2Status = QtWidgets.QLineEdit(EnergyAuditor)
        self.node2Status.setGeometry(QtCore.QRect(455, 195, 16, 16))
        self.node2Status.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.node2Status.setObjectName("node2Status")
        self.node3TimeLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node3TimeLabel.setGeometry(QtCore.QRect(610, 255, 51, 51))
        self.node3TimeLabel.setText("")
        self.node3TimeLabel.setPixmap(QtGui.QPixmap("Images/clock.png"))
        self.node3TimeLabel.setObjectName("node3TimeLabel")
        self.node3Status = QtWidgets.QLineEdit(EnergyAuditor)
        self.node3Status.setGeometry(QtCore.QRect(690, 195, 16, 16))
        self.node3Status.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.node3Status.setObjectName("node3Status")
        self.node1Label = QtWidgets.QLabel(EnergyAuditor)
        self.node1Label.setGeometry(QtCore.QRect(40, 155, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node1Label.setFont(font)
        self.node1Label.setFrameShape(QtWidgets.QFrame.Box)
        self.node1Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.node1Label.setObjectName("node1Label")
        self.line = QtWidgets.QFrame(EnergyAuditor)
        self.line.setGeometry(QtCore.QRect(260, 140, 20, 351))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(EnergyAuditor)
        self.line_2.setGeometry(QtCore.QRect(510, 140, 20, 351))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(EnergyAuditor)
        self.line_3.setGeometry(QtCore.QRect(0, 480, 761, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(EnergyAuditor)
        self.line_4.setGeometry(QtCore.QRect(0, 132, 761, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.node2Label = QtWidgets.QLabel(EnergyAuditor)
        self.node2Label.setGeometry(QtCore.QRect(290, 155, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node2Label.setFont(font)
        self.node2Label.setFrameShape(QtWidgets.QFrame.Box)
        self.node2Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.node2Label.setObjectName("node2Label")
        self.node3Label = QtWidgets.QLabel(EnergyAuditor)
        self.node3Label.setGeometry(QtCore.QRect(530, 155, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node3Label.setFont(font)
        self.node3Label.setFrameShape(QtWidgets.QFrame.Box)
        self.node3Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.node3Label.setObjectName("node3Label")
        self.node2CurrentLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node2CurrentLabel.setGeometry(QtCore.QRect(325, 382, 46, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node2CurrentLabel.setFont(font)
        self.node2CurrentLabel.setText("")
        self.node2CurrentLabel.setPixmap(QtGui.QPixmap("Images/current.png"))
        self.node2CurrentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.node2CurrentLabel.setObjectName("node2CurrentLabel")
        self.node2PowerLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node2PowerLabel.setGeometry(QtCore.QRect(430, 375, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node2PowerLabel.setFont(font)
        self.node2PowerLabel.setText("")
        self.node2PowerLabel.setPixmap(QtGui.QPixmap("Images/power.png"))
        self.node2PowerLabel.setObjectName("node2PowerLabel")
        self.node3CurrentLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node3CurrentLabel.setGeometry(QtCore.QRect(555, 382, 46, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node3CurrentLabel.setFont(font)
        self.node3CurrentLabel.setText("")
        self.node3CurrentLabel.setPixmap(QtGui.QPixmap("Images/current.png"))
        self.node3CurrentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.node3CurrentLabel.setObjectName("node3CurrentLabel")
        self.node3PowerLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node3PowerLabel.setGeometry(QtCore.QRect(655, 375, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node3PowerLabel.setFont(font)
        self.node3PowerLabel.setText("")
        self.node3PowerLabel.setPixmap(QtGui.QPixmap("Images/power.png"))
        self.node3PowerLabel.setObjectName("node3PowerLabel")
        self.node1CurrentLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node1CurrentLabel.setGeometry(QtCore.QRect(55, 382, 46, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node1CurrentLabel.setFont(font)
        self.node1CurrentLabel.setText("")
        self.node1CurrentLabel.setPixmap(QtGui.QPixmap("Images/current.png"))
        self.node1CurrentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.node1CurrentLabel.setObjectName("node1CurrentLabel")
        self.node1PowerLabel = QtWidgets.QLabel(EnergyAuditor)
        self.node1PowerLabel.setGeometry(QtCore.QRect(155, 375, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.node1PowerLabel.setFont(font)
        self.node1PowerLabel.setText("")
        self.node1PowerLabel.setPixmap(QtGui.QPixmap("Images/power.png"))
        self.node1PowerLabel.setObjectName("node1PowerLabel")
        self.node1AddressDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1AddressDisplay.setGeometry(QtCore.QRect(75, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1AddressDisplay.setFont(font)
        self.node1AddressDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node1AddressDisplay.setObjectName("node1AddressDisplay")
        self.node2AddressDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node2AddressDisplay.setGeometry(QtCore.QRect(340, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node2AddressDisplay.setFont(font)
        self.node2AddressDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node2AddressDisplay.setObjectName("node2AddressDisplay")
        self.node3AddressDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node3AddressDisplay.setGeometry(QtCore.QRect(575, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node3AddressDisplay.setFont(font)
        self.node3AddressDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node3AddressDisplay.setObjectName("node3AddressDisplay")
        self.node1CurrentDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1CurrentDisplay.setGeometry(QtCore.QRect(35, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1CurrentDisplay.setFont(font)
        self.node1CurrentDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node1CurrentDisplay.setObjectName("node1CurrentDisplay")
        self.node1PowerDisplay = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1PowerDisplay.setGeometry(QtCore.QRect(140, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1PowerDisplay.setFont(font)
        self.node1PowerDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.node1PowerDisplay.setObjectName("node1PowerDisplay")
        self.node1CurrentDisplay_2 = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1CurrentDisplay_2.setGeometry(QtCore.QRect(300, 430, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1CurrentDisplay_2.setFont(font)
        self.node1CurrentDisplay_2.setAlignment(QtCore.Qt.AlignCenter)
        self.node1CurrentDisplay_2.setObjectName("node1CurrentDisplay_2")
        self.node1PowerDisplay_2 = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1PowerDisplay_2.setGeometry(QtCore.QRect(415, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1PowerDisplay_2.setFont(font)
        self.node1PowerDisplay_2.setAlignment(QtCore.Qt.AlignCenter)
        self.node1PowerDisplay_2.setObjectName("node1PowerDisplay_2")
        self.node1CurrentDisplay_3 = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1CurrentDisplay_3.setGeometry(QtCore.QRect(535, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1CurrentDisplay_3.setFont(font)
        self.node1CurrentDisplay_3.setAlignment(QtCore.Qt.AlignCenter)
        self.node1CurrentDisplay_3.setObjectName("node1CurrentDisplay_3")
        self.node1PowerDisplay_3 = QtWidgets.QLineEdit(EnergyAuditor)
        self.node1PowerDisplay_3.setGeometry(QtCore.QRect(640, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.node1PowerDisplay_3.setFont(font)
        self.node1PowerDisplay_3.setAlignment(QtCore.Qt.AlignCenter)
        self.node1PowerDisplay_3.setObjectName("node1PowerDisplay_3")

        self.retranslateUi(EnergyAuditor)
        self.exitButton.clicked.connect(EnergyAuditor.close)
        self.exitButton.clicked.connect(EnergyAuditor.close)
        QtCore.QMetaObject.connectSlotsByName(EnergyAuditor)

    def retranslateUi(self, EnergyAuditor):
        _translate = QtCore.QCoreApplication.translate
        EnergyAuditor.setWindowTitle(_translate("EnergyAuditor", "Energy Auditor"))
        self.node1Label.setText(_translate("EnergyAuditor", "SENSOR NODE 1"))
        self.node2Label.setText(_translate("EnergyAuditor", "SENSOR NODE 2"))
        self.node3Label.setText(_translate("EnergyAuditor", "SENSOR NODE 3"))

